name: tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - atari_py=0.2 # used only in chapter 18
  - box2d-py=2.3 # used only in chapter 18
  - ftfy=5.8 # used only in chapter 16 by the transformers library
  - graphviz # used only in chapter 6 for dot files
  - gym=0.18 # used only in chapter 18
  - ipython=7.20 # a powerful Python shell
  - ipywidgets=7.6 # optionally used only in chapter 12 for tqdm in Jupyter
  - joblib=0.14 # used only in chapter 2 to save/load Scikit-Learn models
  - jupyter=1.0 # to edit and run Jupyter notebooks
  - matplotlib=3.3 # beautiful plots. See tutorial tools_matplotlib.ipynb
  - nbdime=2.1 # optional tool to diff Jupyter notebooks
  - nltk=3.4 # optionally used in chapter 3, exercise 4
  - numexpr=2.7 # used only in the Pandas tutorial for numerical expressions
  - numpy=1.19 # Powerful n-dimensional arrays and numerical computing tools
  - opencv=4.5 # used only in chapter 18 by TF Agents for image preprocessing
  - pandas=1.2 # data analysis and manipulation tool
  - pillow=8.1 # image manipulation library, (used by matplotlib.image.imread)
  - pip # Python's package-management system
  - py-xgboost=0.90 # used only in chapter 7 for optimized Gradient Boosting
  - pyglet=1.5 # used only in chapter 18 to render environments
  - pyopengl=3.1 # used only in chapter 18 to render environments
  - python=3.7 # Python! Not using latest version as some libs lack support
  - python-graphviz # used only in chapter 6 for dot files
 #- pyvirtualdisplay=1.3 # used only in chapter 18 if on headless server
  - requests=2.25 # used only in chapter 19 for REST API queries
  - scikit-learn=0.24 # machine learning library
  - scipy=1.6 # scientific/technical computing library
  - tqdm=4.56 # a progress bar library
  - transformers=4.3 # Natural Language Processing lib for TF or PyTorch
  - wheel # built-package format for pip
  - widgetsnbextension=3.5 # interactive HTML widgets for Jupyter notebooks
  - pip:
    - tensorboard-plugin-profile==2.4.0 # profiling plugin for TensorBoard
    - tensorboard==2.4.1 # TensorFlow's visualization toolkit
    - tensorflow-addons==0.12.1 # used only in chapter 16 for a seq2seq impl.
    - tensorflow-datasets==3.0.0 # datasets repository, ready to use
    - tensorflow-hub==0.9.0 # trained ML models repository, ready to use
    - tensorflow-probability==0.12.1 # Optional. Probability/Stats lib.
    - tensorflow-serving-api==2.4.1 # or tensorflow-serving-api-gpu if gpu
    - tensorflow==2.4.1 # Deep Learning library
    - tf-agents==0.7.1 # Reinforcement Learning lib based on TensorFlow
    - tfx==0.27.0 # platform to deploy production ML pipelines
    - urlextract==1.2.0 # optionally used in chapter 3, exercise 4
