name: tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - graphviz
  - imageio=2.6.1
  - ipython=7.10.1
  - ipywidgets=7.5.1
  - joblib=0.14.0
  - jupyter=1.0.0
  - matplotlib=3.1.2
  - nbdime=1.1.0
  - nltk=3.4.5
  - numexpr=2.7.0
  - numpy=1.17.3
  - pandas=0.25.3
  - pillow=6.2.1
  - pip
  - py-xgboost=0.90
  - pydot=1.4.1
  - pyopengl=3.1.3b2
  - python=3.7
  - python-graphviz
  - requests=2.22.0
  - scikit-image=0.16.2
  - scikit-learn=0.22
  - scipy=1.3.1
  - tqdm=4.40.0
  - tensorboard=2.0.0
  - tensorflow=2.0.0 # or tensorflow-gpu if gpu
  - tensorflow-addons=0.6.0
  - tensorflow-base=2.0.0
  - tensorflow-datasets=1.2.0
  - tensorflow-estimator=2.0.0
  - tensorflow-hub=0.7.0
  - tensorflow-metadata=0.15.1
  - tensorflow-probability=0.7
  - wheel
  - widgetsnbextension=3.5.1
  - pip:
    - atari-py==0.2.6
    - gym==0.15.4
    - opencv-python==4.1.2.30
    - psutil==5.6.7
    - pyglet==1.3.2
    - tensorflow-data-validation=0.15.0
    - tensorflow-model-analysis=0.15.4
    - tensorflow-serving-api=2.0.0 # or tensorflow-serving-api-gpu if gpu
    - tensorflow-transform=0.15.0
    - tf-agents==0.3.0rc0
    - tfx=0.15.0
    - urlextract==0.13.0
    #- pyvirtualdisplay # add if on headless server
