name: tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - graphviz
  - imageio=2.6.0
  - ipython=7.8.0
  - ipywidgets=7.5.1
  - joblib=0.13.2
  - jupyter=1.0.0
  - matplotlib=3.1.1
  - nbdime=1.1.0
  - nltk=3.4.5
  - numexpr=2.7.0
  - numpy=1.17.2
  - pandas=0.25.1
  - pillow=6.2.0
  - pip=19.2.3
  - py-xgboost=0.90
  - pydot=1.4.1
  - pyopengl=3.1.1a1
  - python=3.7
  - python-graphviz=0.10.1
  - requests=2.22.0
  - scikit-image=0.15.0
  - scikit-learn=0.20.3
  - scipy=1.1.0
  - tqdm=4.36.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - pip:
    - atari-py==0.2.6
    - gym==0.15.3
    - opencv-python==4.1.1.26
    - psutil==5.6.3
    - pyglet==1.3.2
    - tensorboard==2.0.0
    - tensorflow==2.0.0
    - tensorflow-addons==0.6.0
    - tensorflow-data-validation==0.15.0
    - tensorflow-datasets==1.3.0
    - tensorflow-estimator==2.0.0
    - tensorflow-hub==0.6.0
    - tensorflow-metadata==0.15.0
    - tensorflow-model-analysis==0.15.2
    - tensorflow-serving-api==2.0.0
    - tensorflow-transform==0.15.0
    - tf-agents-nightly
    - tfp-nightly
    - tfx==0.15.0rc0
    - urlextract==0.13.0
